language: node_js
cache: npm
node_js:
  - stable
script:
  - npm run test:coveralls
  - npm run build
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_KEY
    skip_cleanup: true
    on:
      tags: true
